// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyA0ec0wZARITIZgmKXOEbsKWaTGBS9DtiI',
  //   appId: '1:470412771179:web:4fd1819d59c457772fd62e',
  //   messagingSenderId: '470412771179',
  //   projectId: 'flutter-starter-6f492',
  //   authDomain: 'flutter-starter-6f492.firebaseapp.com',
  //   storageBucket: 'flutter-starter-6f492.appspot.com',
  //   measurementId: 'G-ST9PQS375H',
  // );

  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'AIzaSyDS1xqKXTvoLoPOD2nFIEyIeBHrZ3Yi_ag',
  //   appId: '1:470412771179:android:aee908d80ce7b8ba2fd62e',
  //   messagingSenderId: '470412771179',
  //   projectId: 'flutter-starter-6f492',
  //   storageBucket: 'flutter-starter-6f492.appspot.com',
  // );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyCMCRSnWndFBhzBjaw_9AVucmLk9H7znRc',
  //   appId: '1:470412771179:ios:a507326c88ba764a2fd62e',
  //   messagingSenderId: '470412771179',
  //   projectId: 'flutter-starter-6f492',
  //   storageBucket: 'flutter-starter-6f492.appspot.com',
  //   iosClientId: '470412771179-4afj6soovudj49r2tq1o14f7no89m2qk.apps.googleusercontent.com',
  //   iosBundleId: 'com.example.starterProjectFlutter',
  // );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyCMCRSnWndFBhzBjaw_9AVucmLk9H7znRc',
  //   appId: '1:470412771179:ios:a507326c88ba764a2fd62e',
  //   messagingSenderId: '470412771179',
  //   projectId: 'flutter-starter-6f492',
  //   storageBucket: 'flutter-starter-6f492.appspot.com',
  //   iosClientId: '470412771179-4afj6soovudj49r2tq1o14f7no89m2qk.apps.googleusercontent.com',
  //   iosBundleId: 'com.example.starterProjectFlutter',
  // );
// }
